name: CISDSCResourceGeneration Pester Tests

on:
  pull_request:
    branches:
    - main
    paths:
    - 'src/CISDSCResourceGeneration/**'
    - 'test/**'
    - '!test/CISDSC.Tests.ps1'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: tools\install_dependencies.ps1
      shell: pwsh
    - name: Run tests PowerShell 5
      run: Invoke-Pester -Path '.\test\CISDSCResourceGeneration.Tests.ps1' -CI -Output Detailed
      shell: pwsh