
name: PublishToGallery

on:
  release:
    types: [created]
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: Install-Module -Name 'PSDepend' -Force -SkipPublisherCheck; Invoke-PSDepend -Force
      shell: pwsh
    - name: Run publish script
      env:
        NuGetApiKey: ${{ secrets.NuGetApiKey }}
      run: .github\workflows\PublishToGallery.ps1
      shell: pwsh
